### PR TITLE
Add documentation for the email editor hooks - MAILPOET-5597

### PR DESCRIPTION
**Pull request by triple0t**
## Description

Add documentation for the email editor hooks

## Code review notes

I believe this PR covers the currently available hooks. Do take a look and let me know if you want to make any other additions. 

## QA notes

We can skip QA

## Linked PRs

_N/A_

## Linked tickets

[MAILPOET-5597](https://mailpoet.atlassian.net/browse/MAILPOET-5597)

## After-merge notes

_N/A_

## Tasks

- [ ] I followed [best practices](https://codex.wordpress.org/I18n_for_WordPress_Developers) for translations
- [ ] I added sufficient test coverage
- [ ] I embraced TypeScript by either creating new files in TypeScript or converting existing JavaScript files when making changes

[MAILPOET-5597]: https://mailpoet.atlassian.net/browse/MAILPOET-5597?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by lysyjan** [comment]
@triple0t Thank you for working on it. Because we want to merge soon [the draft adding templates support](https://github.com/mailpoet/mailpoet/pull/5564/files), I would prefer to wait with it and update this PR after merging. What do you think about it?

**Comment by triple0t** [comment]
> Because we want to merge soon [the draft adding templates support](https://github.com/mailpoet/mailpoet/pull/5564/files), I would prefer to wait with it and update this PR after merging. What do you think about it?

@lysyjan  Sure! that's a great idea. I'm okay with waiting 👍🏽

**Comment by lysyjan** [comment]
@triple0t The pull request was merged, so I'm returning it to you.

**Comment by triple0t** [comment]
@lysyjan  All done. Thanks

**Review by lysyjan — APPROVED** [review]

**Pull request merged**
