### PR TITLE
Add simple mixpanel data for automations [MAILPOET-4535]

### PR DESCRIPTION
**Pull request by websupporter**
## Description
Adds some basic mixpanel data

## QA notes
After making sure in [MAILPOET-4535] that the trigger based count is for active workflows only, I renamed it a bit to 
`Automation > Number of "<trigger>" active workflows` to highlight, we only count active workflows at this point.

## Linked tickets
[MAILPOET-4535]

[MAILPOET-4535]: https://mailpoet.atlassian.net/browse/MAILPOET-4535?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MAILPOET-4535]: https://mailpoet.atlassian.net/browse/MAILPOET-4535?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by brezocordero — APPROVED** [review]
LGTM!
Code looks good.
I tested with no workflows and 1 draft. (I was not able to activate the draft on my local site)
Just to be sure, if there are no workflows at all, we still want to send the data, right?

**Comment by websupporter** [comment]
> Just to be sure, if there are no workflows at all, we still want to send the data, right?

I would assume, in case there are no workflows, we want to send `0` as values.

//cc @NeosinneR

**Comment by NeosinneR** [comment]
> I would assume, in case there are no workflows, we want to send `0` as values.

Correct

**Review by Aschepikov — APPROVED** [review]
This is verified, good job.

**Pull request merged**
