### PR TITLE
Make an option to create coupons dynamically [MAILPOET-4763]

### PR DESCRIPTION
**Pull request by samnajian**
## Description

This PR allows generation of coupons dynamically for some newsletter types.

## Code review notes

Please note that the newsletters that get their coupon codes saved, won't get a new coupon code on next renders.

## QA notes

- Add a coupon block to different types of newsletters.
- Verify that only the standard newsletter keeps the same same coupon code, even after pausing and editing the newsletter, and all the automatic newsletters letters, get a new coupon code for each send-out.
- Please merge it to trunk after the [base PR ](https://github.com/mailpoet/mailpoet/pull/4636) is merged to trunk
## Linked PRs

https://github.com/mailpoet/mailpoet/pull/4636

## Linked tickets

[MAILPOET-4763]

## Additional notes:
- Please merge it to trunk after the [base PR ](https://github.com/mailpoet/mailpoet/pull/4636) is merged to trunk

[MAILPOET-4763]: https://mailpoet.atlassian.net/browse/MAILPOET-4763?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by lysyjan — COMMENTED** [review]
@samnajian It's a pretty small change, but it completely covers the ticket specification, if I understand correctly.
I think that some tests could fit well for this type of change. What do you think? Maybe we can extend the specification of the existing ticket.

**Comment by samnajian** [comment]
@lysyjan some unit tests are added in the [base PR ](https://github.com/mailpoet/mailpoet/pull/4636) which takes care of this, and we've added a [ticket](https://mailpoet.atlassian.net/browse/MAILPOET-4984) to add more tests, I'd prefer leaving more tests to that testing ticket.

**Comment by lysyjan** [comment]
@samnajian Please, can you rebase it?

**Review by lysyjan — APPROVED** [review]

**Review by Aschepikov — APPROVED** [review]
GJ!

**Pull request merged**
