### PR TITLE
Zip size bot test PR

### PR DESCRIPTION
**Pull request by costasovo**

### CODE REVIEW

**Comment by costasovo** [comment]
#size-check

**Comment by costasovo** [comment]
#size-check

**Comment by costasovo** [comment]
#check-size

**Comment by costasovo** [comment]
#check-size

**Comment by JanJakes** [comment]
@costasovo It's too big!!!

**Comment by costasovo** [comment]
#check size

**Comment by costasovo** [comment]
#check-size

**Pull request closed without merging**
