### PR TITLE
Wrap WC content with table [MAILPOET-3638]

### PR DESCRIPTION
**Pull request by lysyjan**
[MAILPOET-3638]

I found out that we need to wrap the WC content with another table. The reason is that WC [use another padding](https://github.com/woocommerce/woocommerce/blob/trunk/templates/emails/email-styles.php#L110-L116)

[MAILPOET-3638]: https://mailpoet.atlassian.net/browse/MAILPOET-3638

### CODE REVIEW

**Review by costasovo — DISMISSED** [review]
👍

**Review by veljkho — CHANGES_REQUESTED** [review]
One issue fixed, new arrived:
The whole content is now narrowed. Should be stretched.
[Actual result](https://d.pr/i/lEEKpn)
[Expected result](https://d.pr/i/QL9Pgq)

So as it can be seen, text and the content have big space around, its like added big padding around it.

**Review by costasovo — APPROVED** [review]

**Review by veljkho — CHANGES_REQUESTED** [review]
Unfortunately, it is not good enough.

I see some improvements but the width is not the same it was before, still needs to be stretched.
[Actual result](https://d.pr/i/3SKIO0)t vs [Expected result](https://d.pr/i/QL9Pgq)

There is another issue that has arrived during this PR, it's about `size:` & `print material:` attributes of the product, they should be moved a bit to the right.. check the expected result screenshot. We had this issue in the past and we fixed it, but seems again present in this pull request after changes.

I used Keyboard with size and print select options to test this.

**Comment by lysyjan** [comment]
> There is another issue that has arrived during this PR, it's about `size:` & `print material:` attributes of the product, they should be moved a bit to the right.. check the expected result screenshot. We had this issue in the past and we fixed it, but seems again present in this pull request after changes.

@veljkho I think that this was an issue. When WC sends the email, then the product attributes are without padding on the left. In my opinion, the current state is correct.

**Review by costasovo — APPROVED** [review]

**Review by veljkho — APPROVED** [review]

**Pull request merged**
