### PR TITLE
Line height [MAILPOET-1450]

### PR DESCRIPTION
**Pull request by JanJakes**

### CODE REVIEW

**Comment by JanJakes** [comment]
@amine-mp I'll have a look. I also noticed that this issue requires writing tests so I'll take it back to in-progress and add a couple of tests as well.

**Comment by JanJakes** [comment]
@amine-mp That particular heading in the given template has the following HTML code with inlined styles:

```html
<h1 style="text-align: center; line-height: 46px;"><span style="color: #212327;"><strong style="line-height: 46px;">Your music.<br />Your way.</strong></span></h1>
```

In this case it is expected behavior not to override those styles though I agree it may be very confusing when used in a template.

**Comment by JanJakes** [comment]
@amine-mp Added test, should be ready now.

**Comment by amine-mp** [comment]
That's weird. I can't see how the newsletter editor can add an inline `line-height` to an `h1`, there is no option to do that on the text block and we skip it here https://github.com/mailpoet/mailpoet/blob/master/lib/Newsletter/Renderer/StylesHelper.php#L130

**Pull request merged**
