### PR TITLE
Minor improvements to segmentation code

### PR DESCRIPTION
**Pull request by johnolek**
## Description

This PR includes some refactoring to the segmentation code. The goal was to have better file organization and consistency between subscriber and woo field code.

- Reorganize field files into directories
- Extract woo fields/validation to match how subscriber fields work
- Fix typo in a file name
- Create new FilterProps type instead of repeating it

This would affect the already-open [PR for adding the used shipping method filter](https://github.com/mailpoet/mailpoet/pull/4967), and I'm happy to wait for that to be merged first.

## Code review notes

_N/A_

## QA notes

All of these changes should be true refactors, i.e. not change any functionality. The biggest changes were to frontend files for woocommerce fields, so I think it would be good to focus on ensuring those fields still work as expected in the UI, especially validation (i.e. not calculating subscribers or allowing saving unless the filter is valid).

## Linked PRs

_N/A_

## Linked tickets

_N/A_

## After-merge notes

_N/A_

### CODE REVIEW

**Review by rodrigoprimo — COMMENTED** [review]
Looks good to me. Thanks for taking the time to improve this part of the code base.

For a similar PR in the future, I would suggest splitting the changes into multiple commits. Different reviewers might have different perspectives, but at least for me, having multiple commits, one for each of the changes would have made reviewing this PR a bit easier. Please let me know if, for some reason, you prefer the approach with a single commit.

**Review by rodrigoprimo — APPROVED** [review]
I meant to approve the PR in the first review but I failed to do that :-)

**Comment by johnolek** [comment]
@rodrigoprimo Thanks for the review!

> For a similar PR in the future, I would suggest splitting the changes into multiple commits.

I agree 100%, and that was my original intention. A filter that was merged in after I started this work ended up causing lots of merge conflicts when I rebased this branch. There were many conflicts to resolve for each commit (I did start with multiple), and I was worried I might miss something or make a mistake having to do it so many times, so I squashed the commits so I only needed to resolve the conflicts once.

In any case, I'll try to be more careful and granular about my committing in the future. Thank you for this comment!

**Comment by rodrigoprimo** [comment]
Thanks for the additional context, John!

**Comment by johnolek** [comment]
FYI @Aschepikov and/or @veljkho, I added the `priority in QA` label just because it will be nice to have this merged for other segmentation PRs, like #4990 which I based on this branch, but it's not exactly a priority to get this code itself into a release. If that's not what you would consider a priority feel free to remove the label.

**Comment by Aschepikov** [comment]
Hi @johnolek  this https://github.com/mailpoet/mailpoet/pull/4967 this pr is not ready for testing yet and I wanted to wait for it as you commented

**Comment by rodrigoprimo** [comment]
@Aschepikov, it is fine to test and merge this on,e and then I will rebase #4967 and fix the conflicts.

**Review by Aschepikov — APPROVED** [review]
GJ!

**Pull request merged**
