### PR TITLE
Second pass at deprecating models NewsletterOption and NewsletterOptionField [MAILPOET-4389]

### PR DESCRIPTION
**Pull request by rodrigoprimo**
This PR is the second attempt to deprecate the models NewsletterOption and NewsletterOptionField. The first attempt #4126 had to be reverted in #4135 due to some code that was deprecated but still used in our codebase. We only caught this when #4126 was merged to trunk because it seems the error levels for the acceptance tests seem to differ between CircleCI builds for PRs and the nightly build. This will be addressed in a separate PR (see https://mailpoet.atlassian.net/browse/MAILPOET-4354). More information about the warning that happened when the original PR was merged can be found here: https://app.slack.com/client/T024FN1V2/C01H71ZLBGQ/thread/C01H71ZLBGQ-1652779279.594339

Initially, the plan was to work first on MAILPOET-4354 to consolidate the error levels between different CircleCI builds and then work on this PR. But I spent some time on MAILPOET-4354 and couldn't find anything easily, and I also noticed that the code that was causing the warning for the code changes proposed here was already removed from our code base.

The problem when this PR was introduced the first time was that it deprecated Newsletter::filterType(), but this method was still being used in Scheduler::getNewsletters(). That is not the case anymore, and filterType() was removed from getNewsletters() in https://github.com/mailpoet/mailpoet/commit/4ba5c6ce0cd309319173f8b4132a9f7ecb57f9e6#diff-1d581175bab2c67d713e5e2de493065591c1b93896e1061caf91a2f2c96e451eL70

[MAILPOET-4389]

[MAILPOET-4389]: https://mailpoet.atlassian.net/browse/MAILPOET-4389?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by JanJakes — DISMISSED** [review]
Great! 👏

**Comment by veljkho** [comment]
Hi @rodrigoprimo 
I see one conflicting file here, can you please rebase it? Thanks.

**Comment by rodrigoprimo** [comment]
Thanks for the ping, @veljkho. I have merged changes from trunk and fixed the conflict.

**Review by veljkho — DISMISSED** [review]

**Comment by veljkho** [comment]
Hi @rodrigoprimo 
I can't merge because of some conflicts... but I don't see which files are conflicting.

**Comment by rodrigoprimo** [comment]
Thanks for the ping, @veljkho. I'm not sure as well what was going on here. I tried merging trunk into this PR and got no conflicts. If I tried to rebase trunk into this PR I got one conflict and some weird results. In the end, I decided to create a new branch and cherry-picked all the commits from the original branch. That seems to have worked well and now there are no more conflicts.

**Review by veljkho — APPROVED** [review]

**Pull request merged**
