### PR TITLE
Mention both forms and emails when describing 3rd-party libraries and Google Fonts [MAILPOET-4888]

### PR DESCRIPTION
**Pull request by NeosinneR**
## Description

Updated 3rd-party libraries description in Settings and Welcome Wizard to mention both Forms and Emails editors. 

## Code review notes

_N/A_

## QA notes

_N/A_

## Linked PRs

_N/A_

## Linked tickets

[MAILPOET-4888]

## After-merge notes

_N/A_

[MAILPOET-4888]: https://mailpoet.atlassian.net/browse/MAILPOET-4888?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by websupporter — COMMENTED** [review]
> E.g. Google Fonts (used in Form and Email editors) and HelpScout (used for support). This needs to be enabled if you want to be able to contact support.

Not myself a native speaker, but this sounds a bit clunky to me, especially the "used in Form and Email editors" part. Maybe better: "(used in the Form and the Email editor)"?

**Comment by NeosinneR** [comment]
@websupporter updated. Added one more `editor` so it's fully covered (also in line with what Kelly originally suggested in the ticket).

**Review by websupporter — APPROVED** [review]
lgtm

**Review by Aschepikov — APPROVED** [review]
GJ!

**Pull request merged**
