### PR TITLE
Add Parsley validation to the manage form [MAILPOET-3928]

### PR DESCRIPTION
**Pull request by lysyjan**
[MAILPOET-3928]

[MAILPOET-3928]: https://mailpoet.atlassian.net/browse/MAILPOET-3928?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by rodrigoprimo — COMMENTED** [review]
Good job, @lysyjan. I can confirm that with the changes proposed here, the validation works on the "Manage subscription" page.

The only concern that I have is that @triple0t mentioned potential security issues. If there is any, I fear that client-side validation is not enough as it is usually pretty easy to bypass and we should validate and/or sanitize also on the server-side. I haven't checked the code deeply to verify potential security issues and whether or not it is worth implementing server-side validation. Generally speaking, I tend to err on the side of caution and assume it is worth doing it unless proven otherwise.

@triple0t, do you have any concrete security concerns in mind?

@lysyjan, what do you think?

**Comment by lysyjan** [comment]
@rodrigoprimo Because a custom field can be without validation, I think the current solution is enough.

**Comment by rodrigoprimo** [comment]
@triple0t, just a friendly reminder about the question above in case you missed it.

**Comment by triple0t** [comment]
@rodrigoprimo @lysyjan I believe this is good to go.

**Review by rodrigoprimo — APPROVED** [review]

**Pull request merged**
