### PR TITLE
Show status for deactivating workflows [MAILPOET-4941]

### PR DESCRIPTION
**Pull request by websupporter**
## Description

_N/A_

## Code review notes

_N/A_

## QA notes

_N/A_

## Linked PRs

_N/A_

## Linked tickets

[MAILPOET-4941]

## After-merge notes

_N/A_

## Tasks

- [x] I followed [best practices](https://codex.wordpress.org/I18n_for_WordPress_Developers) for translations
- [x] I added sufficient test coverage
- [x] I embraced TypeScript by either creating new files in TypeScript or converting existing JavaScript files when making changes

[MAILPOET-4941]: https://mailpoet.atlassian.net/browse/MAILPOET-4941?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by johnolek — APPROVED** [review]
LGTM!

**Comment by Aschepikov** [comment]
Hi, @websupporter  The deactivating status should be shown when the active automation has some "total processing"?

**Comment by websupporter** [comment]
Hi @Aschepikov,
image

"Deactivating" means you want to deactivate the automation (which means putting it back to draft) while you wish the existing runs to complete and not be cancelled.

**Review by Aschepikov — APPROVED** [review]
Thank you for the explanation, gj!

**Pull request merged**
