### PR TITLE
Automatic emails to automations [MAILPOET-5779]

### PR DESCRIPTION
**Pull request by JanJakes**
## Description

Legacy automatic emails (welcome emails & WooCommerce emails) were moved to automation listing.
It is no longer possible to create those emails, we're moving to automations.
New email page got a facelift.

## Code review notes

Skipping code review as per: https://codep2.wordpress.com/2023/12/08/experiment-code-reviews-optional-in-january/

## QA notes

1. Before switching to this branch, prepare some legacy automatic emails (welcome emails & WooCommerce emails), and related data (some sent, some scheduled, etc.).
2. Then, switch to the build from this branch that those are displayed on the automation listing page, together with their descriptions and stats.
3. Also check that there are the new notices above the email and automation listings (as per specs).
4. Please, also check the `Emails > New email` page. It was updated and refreshed (as per specs).

## Linked PRs

_N/A_

## Linked tickets

[MAILPOET-5779]

## After-merge notes

_N/A_

## Tasks

- [x] I followed [best practices](https://codex.wordpress.org/I18n_for_WordPress_Developers) for translations
- [x] I added sufficient test coverage
- [x] I embraced TypeScript by either creating new files in TypeScript or converting existing JavaScript files when making changes

[MAILPOET-5779]: https://mailpoet.atlassian.net/browse/MAILPOET-5779?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by Aschepikov** [comment]
Hi @JanJakes  In the specs I see Description = legacy email description + **timing** but I don't see the timing in the automation list 
image
But i see it in the email editor 
image
Can you check it pls

**Comment by Aschepikov** [comment]
HI @JanJakes after the activating of the legacy email in the editor I am redirecting to the old page 
image
Should we change the redirecting of the woocommerce emails?

**Comment by Aschepikov** [comment]
@pavel-mailpoet  Hi can you take a look on it, should we improve this redirecting or it is ok?

**Comment by pavel-mailpoet** [comment]
@Aschepikov Thank you for pointing that out. I think it is ok the way it is now. The new email editor is still experimental and we will be improving it from our end so this Pull Request doesn't have to be blocked for now.

**Review by Aschepikov — APPROVED** [review]
GJ!

**Comment by JanJakes** [comment]
@Aschepikov These redirects are sort of an edge case, but good catch! Fixing them in https://github.com/mailpoet/mailpoet/pull/5379.

**Pull request merged**
