### PR TITLE
WordPress Playground & Studio improvements [MAILPOET-6185]

### PR DESCRIPTION
**Pull request by JanJakes**
## Description

Just a few more fixes for WordPress Playground & Studio, and a notice about this being a plugin preview.

Screenshot 2024-08-30 at 16 57 47

## Code review notes

Please, just see the commit messages. QA can be skipped, I think.

## Linked PRs

https://github.com/mailpoet/mailpoet/pull/5777

## Linked tickets

[MAILPOET-6185]

[MAILPOET-6185]: https://mailpoet.atlassian.net/browse/MAILPOET-6185?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

## Preview

[Preview in WordPress Playground](https://account.mailpoet.com/playground/new/branch:wp-playground-improvements)

_The latest successful build from `wp-playground-improvements` will be used. If none is available, the link won't work._

### CODE REVIEW

**Review by NeosinneR — COMMENTED** [review]
Overall looks good, but what I'm not 100% aligned with is using `Connection::isSQLite()` directly in conditions, as over time, this might get lost about why it's there. 

@JanJakes what do you think about a simple `isWordPressPlayground()` method, that would just call `Connection::isSQLite()`? It would improve the readability and in future it's easier to update if it's no longer needed or we have a better way to detect Playground (e.g. via a constant).

**Comment by JanJakes** [comment]
@NeosinneR I agree that the  `Connection::isSQLite()` should be reviewed at some point, but at the moment, it's probably the best test because it really kind of is about https://github.com/WordPress/sqlite-database-integration/, which is used by both Playground and Studio, and the Studio support is also a priority at the moment (https://github.com/Automattic/studio/issues/132). In the future, there might be differences between the Playground and Studio usage, etc. It will need some more thought, I guess.

I would now take it as a quick and a bit hacky way to get it off the ground, and later we surely should improve that.

**Review by NeosinneR — DISMISSED** [review]

**Comment by NeosinneR** [comment]
@JanJakes ah, I approved this already, but noticed, that the Playground link should probably include `branch:`?

**Comment by JanJakes** [comment]
@NeosinneR

> @JanJakes ah, I approved this already, but noticed, that the Playground link should probably include `branch:`? 

🤦‍♂️ Yes, for sure. Let me quickly fix that. Btw. is it possible to change a branch name in the same PR? Just wondering if the logic of the GitHub action should be more of "create or update" than "create or ignore". That said, we can improve that later.

**Comment by JanJakes** [comment]
@NeosinneR Repushed.

**Review by NeosinneR — APPROVED** [review]
> is it possible to change a branch name in the same PR?

I don't think so, or at least I wasn't able to find a way to do so. And I don't remember us doing that in the past, so even if possible, probably a rare case we don't have to accommodate.

**Pull request merged**
