### PR TITLE
Move Twig to prefixed dependencies [MAILPOET-1929]

### LINKED ISSUE #1904: Update Twig dependency
If I see it correctly you are shipping with Twig 1.38.0 and I would like to request an update to 1.38.3 which fixes a few things that are required for [Podlove Publisher plugin](https://github.com/podlove/podlove-publisher/issues/1039). And it looks like your version of Twig gets precendence when loading over the version I include in the plugin so a quick fix would be very much appreciated :)

### PR DESCRIPTION
**Pull request by pavel-mailpoet**
Closes #1904

### CODE REVIEW

**Comment by pavel-mailpoet** [comment]
Thanks @michelleshull but I need to see where exactly the error is. How to replicate it.

**Comment by michelleshull** [comment]
@pavel - sure, just install and activate https://wordpress.org/plugins/podlove-podcasting-plugin-for-wordpress/ The fatal error appears as soon as you try to attempt to have both plugins active at once.

**Comment by costasovo** [comment]
There was still a conflict since some some prefixed classes were aliased as global not prefixed.
It seems that now we need a new reviewer...

**Comment by michelleshull** [comment]
No more fatal errors, even with all the conflicting plugins active at once. Nice!

**Pull request merged**
