### PR TITLE
Revert "Revert "Process arguments better when querying posts for automated latest content [MAILPOET-4082]""

### PR DESCRIPTION
**Pull request by samnajian**
Reverts mailpoet/mailpoet#4068

Testing:

Note: This pull request doesn't have simple steps to test it. This change is directly affecting Post Notifications part of the plugin. Please test that it is working as expected, here are some tips to test it:

1. Go to Posts and make a 1-2 posts and make sure you have received Post Notification email about the latest posts on site
2. Go to MailPoet > Emails > Post Notifications tab
3. Edit the existing or create a new post notification email but make sure to test ALC (Automatic Latest Content) block and its settings in the right sidebar (click the block to see the right sidebar and then click `Display Options` link to see full settings of the block)
4. Test receiving PN email after you make some changes/tests of that ALC block

### CODE REVIEW

**Comment by rodrigoprimo** [comment]
Regarding the commit 7bdb23999c5b8df692669339489b93b74512cc14, I would suggest that for future commits, more details about what was failing, why it was failing, and what is the fix is included in the commit message. This should help us in the future when debugging future issues and trying to understand a particular change.

**Comment by rodrigoprimo** [comment]
One final note, I don't understand why GitHub is showing that the CircleCI build_release_zip job is still pending as it shows as completed on CircleCI.

**Comment by samnajian** [comment]
> One final note, I don't understand why GitHub is showing that the CircleCI build_release_zip job is still pending as it shows as completed on CircleCI.

Seems like another hickup from Github, I'd keep this under radar and see if this happens in the coming days as well

**Comment by rohankacharegs** [comment]
GlobalStep Verified

**Review by veljkho — APPROVED** [review]

**Pull request merged**
