### PR TITLE
Landing page improvements [MAILPOET-5262]

### PR DESCRIPTION
**Pull request by NeosinneR**
## Description

Landing page (`admin.php?page=mailpoet-landingpage`) changes:

- Updated copy
- Added Automations feature
- Updated images to be retina
- Made the whole page more compact 
- Made the grey section background full-width

## Code review notes

_N/A_

## QA notes

New images are not yet uploaded in CDN, but they can be tested locally, when `MAILPOET_USE_CDN` is set to false.

## Linked PRs

_N/A_

## Linked tickets

[MAILPOET-5262]

## After-merge notes

_N/A_

## Tasks

- [x] I followed [best practices](https://codex.wordpress.org/I18n_for_WordPress_Developers) for translations
- [x] 🚫 I added sufficient test coverage
- [x] 🚫 I embraced TypeScript by either creating new files in TypeScript or converting existing JavaScript files when making changes

[MAILPOET-5262]: https://mailpoet.atlassian.net/browse/MAILPOET-5262?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by costasovo — DISMISSED** [review]
@NeosinneR Thanks for the update!

**Comment by Aschepikov** [comment]
Hi @NeosinneR  just wanted to ask for sure, I don't see these changes in the questions like in the doc file
image
is it expected?

**Comment by NeosinneR** [comment]
@Aschepikov good catch. That was an oversight. Added those in the new commit.

**Review by Aschepikov — APPROVED** [review]
GJ!

**Pull request merged**
