### PR TITLE
Add check that function error_log exists [MAILPOET-5026]

### PR DESCRIPTION
**Pull request by lysyjan**
## Description

_N/A_

## Code review notes

_N/A_

## QA notes

_N/A_

## Linked PRs

_N/A_

## Linked tickets

[MAILPOET-5026]

## After-merge notes

_N/A_

[MAILPOET-5026]: https://mailpoet.atlassian.net/browse/MAILPOET-5026?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by samnajian — APPROVED** [review]
LGTM

**Review by veljkho — APPROVED** [review]

**Comment by JanJakes** [comment]
Oh, wow, I'll never stop being surprised by all the cases that we need to handle 🙀

Do you, @lysyjan and @samnajian think, that to avoid this in the future, it might be better to "polyfill" such functions when bootstrapping the plugin? If we do something like this, then we will never forget to use an IF:

```php
// a dummy polyfill that does nothing
if (!function_exists('error_log')) {
  function error_log(string $error) {}
}
```

**Comment by samnajian** [comment]
@JanJakes I agree that polyfilling is probbaly a better approach, thanks for the idea, @lysyjan we can add it as an improvement, what do you think?

**Comment by JanJakes** [comment]
If you guys agree with this, we could create a ticket for that, and have a look, if we use IFs for any other functions that tend to be disabled.

**Comment by lysyjan** [comment]
@JanJakes @samnajian I like this proposal!

**Comment by JanJakes** [comment]
https://mailpoet.atlassian.net/browse/MAILPOET-5108

**Pull request merged**
