### PR TITLE
Fix finding subscriber [MAILPOET-4184]

### PR DESCRIPTION
**Pull request by websupporter**
Fixes [MAILPOET-4184]

[MAILPOET-4184]: https://mailpoet.atlassian.net/browse/MAILPOET-4184?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by rodrigoprimo** [comment]
@websupporter, I'm on L2 support this week. Could you please assign this PR to someone else?

**Comment by websupporter** [comment]
Sorry, missed that @rodrigoprimo. Will do

**Comment by rodrigoprimo** [comment]
Thanks!

**Review by lysyjan — APPROVED** [review]
LGTM

**Review by Aschepikov — APPROVED** [review]
GJ!

**Pull request merged**
