### PR TITLE
Optimize transifexrc geenration

### PR DESCRIPTION
**Pull request by szepeviktor**

### CODE REVIEW

**Comment by szepeviktor** [comment]
Some JavaScript error in CI!

**Comment by pavel-mailpoet** [comment]
@szepeviktor Sorry, we had a JS problem on Master, that has been fixed now. Can you rebase your branch, please?

**Comment by szepeviktor** [comment]
Done.

**Comment by szepeviktor** [comment]
> There was 1 failure:
> 
> ---------
> 1) NewsletterCreationCest: Create newsletter when key pending approval
>  Test  tests/acceptance/NewsletterCreationCest.php:createNewsletterWhenKeyPendingApproval
>  Step  Click "[data-automation-id="create_standard"]",null
>  Fail  Link or Button or CSS or XPath element with '[data-automation-id="create_standard"]' was not found.
> 

https://circleci.com/gh/mailpoet/mailpoet/78486

Is it relevant here?

**Comment by pavel-mailpoet** [comment]
> Is it relevant here?

We think there is a missing key to our sending service. That failure should be ok.

@szepeviktor thank you for your PR, we will review it soon.

**Comment by szepeviktor** [comment]
Thank you.

**Comment by costasovo** [comment]
@szepeviktor Thanks!

**Pull request merged**
