### PR TITLE
Redesign send with [MAILPOET-1705]

### PR DESCRIPTION
**Pull request by amine-mp**
[MAILPOET-1705]

[MAILPOET-1705]: https://mailpoet.atlassian.net/browse/MAILPOET-1705

### CODE REVIEW

**Review by wxa — CHANGES_REQUESTED** [review]
Specs 5.a.i.2 and 5.a.ii.2 say that when a key is not valid for MSS:
> Choosing the radio input will switch to Key activation tab

This does not happen: nothing changes when I click the MSS radio input with an invalid key.

**Review by wxa — DISMISSED** [review]

**Review by veljkho — CHANGES_REQUESTED** [review]
Everything's good except one thing:
- I see all the time "Solve all of your sending problems" message but even after I fixed everything. Seems the message is stuck always.
Hint: Maybe it was caused by above message for inappropriate version? [Screenshot](https://i.imgur.com/iYgMCYv.png)
Are they related? If yes, than this issue might not be valid.

**Comment by NeosinneR** [comment]
@veljkho I'm not sure I understand it correctly, but `Solve all of your sending problems` is a description for MSS option, it should be always visible

**Comment by NeosinneR** [comment]
@veljkho I stand corrected, I haven't realized, that currently, when MSS is active, there is `You're now sending with MailPoet!` instead. We should keep the same functionality even after the redesign. I'll update specs

**Review by wxa — APPROVED** [review]

**Review by veljkho — APPROVED** [review]

**Pull request merged**
