### PR TITLE
Bump WP require at least to 6.0 and tested up to 6.2 [MAILPOET-5075]

### PR DESCRIPTION
**Pull request by rodrigoprimo**
## Description

This PR simply bumps up the required at least and tested up to WP versions to 6.0 and 6.2, respectively.

## Code review notes

_N/A_

## QA notes

Per the documentation, please check with QA if they want to do a final test of WP 6.2 or not. Probably not necessary since this WP version was released a while ago, and no problems were reported.

## Linked PRs

_N/A_

## Linked tickets

[MAILPOET-5075]

## After-merge notes

_N/A_

[MAILPOET-5075]: https://mailpoet.atlassian.net/browse/MAILPOET-5075?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by rodrigoprimo** [comment]
I just force pushed new commits to fix a conflict with trunk.

**Review by brezocordero — DISMISSED** [review]
Looks good.
@veljkho The automated tests have been updated on: https://github.com/mailpoet/mailpoet/pull/4886
Please merge if you think there is no need for QA.

**Comment by veljkho** [comment]
Hi @rodrigoprimo 
Please there is one conflicting file, after that I can merge. Thanks!

**Comment by rodrigoprimo** [comment]
@veljkho, I just fixed the conflict. Thanks.

**Review by veljkho — APPROVED** [review]

**Pull request merged**
