### PR TITLE
Increase number of checks if the email was sent in automation [MAILPOET-6175]

### PR DESCRIPTION
**Pull request by JanJakes**
## Description

When an automation schedules an email to be sent, the sending process should trigger an automation step to progress immediately after sending. However, this can sometimes fail for various reasons (timeout, server restart/crash, etc.). To catch such cases (and cases when an email was never sent), we use a progress step that is scheduled in the future to check how the email sending action ended. At the moment, there is a single check after one month. This PR adds more of these checks in an "exponential backoff" fashion.

## Code review notes

_N/A_

## QA notes

Please verify that send email step in automations works and that the automation correctly proceeds after sending. I don't think it's necessary to try to replicate exactly this particular issue, as it's hard to do and there is a test for that.

## Linked PRs

_N/A_

## Linked tickets

[MAILPOET-6175]

## After-merge notes

_N/A_

## Tasks

- [x] I followed [best practices](https://codex.wordpress.org/I18n_for_WordPress_Developers) for translations
- [x] I added sufficient test coverage
- [x] I embraced TypeScript by either creating new files in TypeScript or converting existing JavaScript files when making changes

[MAILPOET-6175]: https://mailpoet.atlassian.net/browse/MAILPOET-6175?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by lysyjan — DISMISSED** [review]
LGTM 👍

**Review by Aschepikov — DISMISSED** [review]
GJ!

**Comment by Aschepikov** [comment]
Hi @JanJakes there are some conflicts can you resolve them pls

**Comment by JanJakes** [comment]
@Aschepikov Repushed ✅

**Pull request merged**
