### PR TITLE
Redesign email schedule [MAILPOET-2787]

### PR DESCRIPTION
**Pull request by NeosinneR**
[MAILPOET-2787]

@veljkho this PR also redesigned form controls, which are used at the last step of email creation, list/segment/subscriber edit and probably somewhere else, so when QAing, please have a look throughout the plugin to see if everything works.

[MAILPOET-2787]: https://mailpoet.atlassian.net/browse/MAILPOET-2787

### CODE REVIEW

**Review by wxa — APPROVED** [review]
Looks fine. The only difference with the design is gray background instead of a white one, but @NeosinneR said it will be fixed in phase 7 along with other pages.

**Comment by wxa** [comment]
@NeosinneR I've checked other pages that could be affected by global style changes form this PR, there are a few things:
1. Counts in listing categories are misplaced a bit.
2. The font size in listing rows is a bit small to my eyesight, easily solvable by zooming a page in, though.
3. Scheduling of standard newsletters on the last step needs tidying up (vertical centering at least).

**Review by wxa — CHANGES_REQUESTED** [review]
See my previous comment.

**Comment by NeosinneR** [comment]
@wxa points 1. and 3. fixed, I left 2. untouched for now but will check back when listings are redesigned

**Review by wxa — APPROVED** [review]

**Review by veljkho — APPROVED** [review]

**Pull request merged**
