### PR TITLE
Fix link to buy the agency license of MailPoet Premium [MAILPOET-3384]

### PR DESCRIPTION
**Pull request by rodrigoprimo**
[MAILPOET-3384]

[MAILPOET-3384]: https://mailpoet.atlassian.net/browse/MAILPOET-3384

### CODE REVIEW

**Review by lysyjan — DISMISSED** [review]

**Review by veljkho — CHANGES_REQUESTED** [review]
Issue with the improper link is fixed. 
But the issue with incorrect button label is still present. We should remove `(currently 33% discount)` from the button as well.

**Comment by rodrigoprimo** [comment]
@veljkho, please correct me if I'm mistaken, but I didn't look into changing the label of the button because what I understood from @NeosinneR's comment on the Jira issue is that he wanted us to fix just the link.

**Comment by NeosinneR** [comment]
@rodrigoprimo a slight misunderstanding here. The label should also be changed (to remove the 33% discount). The Jira ticket description previously contained two issues (one of which was removed from the description) so my comment became obsolete.

**Comment by rodrigoprimo** [comment]
@NeosinneR, thanks for the clarification. I wrongly assumed that the problem that should be ignored was updating the label as I missed that the original description of the issue was edited.

I just updated the label of the button as well. Since this is a fairly small change, I opted to amend the original commit and force push it to the remote branch to keep the git history clean.

In a case like this one where QA asks for changes in a PR, should I request a new review from @veljkho directly, or should I first request a new review from the developer that reviewed the PR?

**Comment by NeosinneR** [comment]
@rodrigoprimo if it's a small change like this, you can assign @veljkho right away

**Review by veljkho — APPROVED** [review]

**Pull request merged**
