### PR TITLE
Update form template header and add footer [MAILPOET-5376]

### PR DESCRIPTION
**Pull request by lysyjan**
## Description

This PR updates the header in the form template selection.

## Code review notes

Compared with the Figma design, I decided not to use the left chevron icon in the heading for better consistency with other headings. Also, spacing should be more consistent with Automation.

## QA notes

Check the new header and footer in the form template selection.

## Linked PRs

_N/A_

## Linked tickets

[MAILPOET-5376]

## After-merge notes

_N/A_

## Tasks

- [x] I followed [best practices](https://codex.wordpress.org/I18n_for_WordPress_Developers) for translations
- [x] I added sufficient test coverage
- [x] I embraced TypeScript by either creating new files in TypeScript or converting existing JavaScript files when making changes

[MAILPOET-5376]: https://mailpoet.atlassian.net/browse/MAILPOET-5376?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by alex-mailpoet** [comment]
@lysyjan Could you please align the button horizontally with the heading?
image

**Comment by lysyjan** [comment]
@alex-mailpoet Which browser did you use? I'm asking because the button is on your screenshot higher than on my staging. Nevertheless, there is space for improvement, so I am going to fix it.
screenshot

**Comment by lysyjan** [comment]
@alex-mailpoet The issue should be addressed in the last commit https://github.com/mailpoet/mailpoet/pull/5061/commits/d6164e65629d5adbc268b88cbb868fce217f33db

**Comment by alex-mailpoet** [comment]
@lysyjan 
> Which browser did you use? 

I used Firefox, sorry for not mentioning it the first time.

Thanks for fixing, now it looks good to me!

**Review by alex-mailpoet — APPROVED** [review]

**Comment by lysyjan** [comment]
@alex-mailpoet That's fine. Thank you for catching it 👍

**Review by Aschepikov — APPROVED** [review]
GJ!

**Pull request merged**
