### PR TITLE
Form Editor: Columns [MAILPOET-2609]

### PR DESCRIPTION
**Pull request by costasovo**
[MAILPOET-2609]

[MAILPOET-2609]: https://mailpoet.atlassian.net/browse/MAILPOET-2609

### CODE REVIEW

**Comment by codemonkey-jack** [comment]
@costasovo I left a comment on the Jira ticket, this fails QA.

**Comment by codemonkey-jack** [comment]
@costasovo Could you resolve the conflicts on this one, please? :)

**Comment by costasovo** [comment]
@pavel-mailpoet I resolved conflicts + added a commit to unify how we handle paddings within a form.

**Comment by costasovo** [comment]
@veljkho Good catch! Thank you!
@pavel-mailpoet I've added a commit with a fix.

**Comment by pavel-mailpoet** [comment]
Approved, back to you @veljkho

**Pull request merged**
