### PR TITLE
Add link to settings on congratulatory page [MAILPOET-4640]

### PR DESCRIPTION
**Pull request by lysyjan**
## Description

_N/A_

## Code review notes

_N/A_

## QA notes

_N/A_

## Linked PRs

_N/A_

## Linked tickets

[MAILPOET-4640](https://mailpoet.atlassian.net/browse/MAILPOET-4640)

## After-merge notes

_N/A_

[MAILPOET-4640]: https://mailpoet.atlassian.net/browse/MAILPOET-4640?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by brezocordero — CHANGES_REQUESTED** [review]
Code looks good!
I also tested on a fresh site, and the message displayed as expected.

Sending it back to you @lysyjan to change the ticket number.
Should be MAILPOET-4640

**Comment by lysyjan** [comment]
@brezocordero I apologize! I have force-pushed the commit with the correct commit message.

**Review by brezocordero — APPROVED** [review]
LGTM!

**Review by Aschepikov — APPROVED** [review]
GJ!

**Pull request merged**
