### PR TITLE
JS/TS translations [MAILPOET-4611]

### PR DESCRIPTION
**Pull request by JanJakes**
## Description

Introduces JS/TS translation extraction (for all of our JS/TS) and loading (for automations-only now). In particular:

1. All PHP and JS/TS translations are now extracted using WP CLI's `i18n` command.
2. The old forked code was reduced to a single script extracting translations from HTML and HBS files only.
3. Those files are merged into a single POT file.
4. We can no longer do JS build content hashing because translations are extracted from the JS dist files, and their file names would change all the time. Instead, we use the WP's `?ver=<plugin-version>` argument.
5. For automation code, we're now using `wp_enqueue_script()` and `wp_set_script_translations()`. In a follow-up task, we'll do that for all of the JS assets.
6. Made all (hopefully) automation strings translatable and improved some comments and context.

## Code review notes

_N/A_

## QA notes

This touches script loading in the plugin, so I'd suggest quickly browsing all pages and subpages, checking if they load and if there are any JS errors in the browser console.

## Linked PRs

https://github.com/mailpoet/mailpoet-premium/pull/637

## Linked tickets

[MAILPOET-4611]

## After-merge notes

_N/A_

[MAILPOET-4611]: https://mailpoet.atlassian.net/browse/MAILPOET-4611?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by JanJakes** [comment]
I talked to @costasovo, and he'd be willing to have a look at this. That said, I'd like to notify also @samnajian and @websupporter, if you guys want to have a look.

**Review by costasovo — DISMISSED** [review]
👏 I'm super happy to see this! Now we can kick out all those strings from twig template files and move them to JS code.

Great job!

**Review by costasovo — DISMISSED** [review]

**Review by Aschepikov — COMMENTED** [review]
Hi, @JanJakes. Verified, GJ!
 Can you please resolve the conflicts?

**Comment by JanJakes** [comment]
@Aschepikov Thanks! Rebased. I wanted to merge it but realized that I'm not sure if the premium part is verified so moving it back to you.

**Review by Aschepikov — APPROVED** [review]
Verified, GJ!

**Pull request merged**
