### PR TITLE
link to the new homepage from the mailpoet task in woocommerce - MAILPOET-4926

### PR DESCRIPTION
**Pull request by triple0t**
## Description

Link to the new homepage from the MailPoet task in WooCommerce

## Code review notes

Please start review from https://github.com/mailpoet/mailpoet/pull/4697/commits/324d706105e942be09ff244ade37cc7ab38ec9f4

## QA notes

You can access the WC admin page here: `/wp-admin/admin.php?page=wc-admin`

* Ensure you have completed the welcome wizard 
* Visit the WC admin page
* Click on the "MailPoet setup completed" task list

**Test case 1**
If you have the New homepage feature enabled (`/wp-admin/admin.php?page=mailpoet-experimental`)
* You should be redirected to the Homepage

**Test case 2**
If you don't have the New homepage feature enabled
* You should be redirected to the Newsletter page

## Linked PRs

Dependent on https://github.com/mailpoet/mailpoet/pull/4660

## Linked tickets

[MAILPOET-4926](https://mailpoet.atlassian.net/browse/MAILPOET-4926)

[MAILPOET-4926]: https://mailpoet.atlassian.net/browse/MAILPOET-4926?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by costasovo — DISMISSED** [review]
👍

**Comment by Aschepikov** [comment]
Hi, @triple0t  can you resolve the conflicts please

**Comment by triple0t** [comment]
> Hi, @triple0t can you resolve the conflicts please

Done @Aschepikov

**Review by Aschepikov — APPROVED** [review]
GJ!

**Pull request merged**
