### PR TITLE
Fix missing icon in Members' plugin [MAILPOET-1804]

### PR DESCRIPTION
**Pull request by NeosinneR**
I'm not really a fan of this solution, because SVG's as background can't be styled with CSS, that's why there are these `filter` "hacks", but I still find it more maintainable then icon font. But I'm open to rewriting it to icon font if this seems too hacky.

FYI, this is used in another plugin, so we can't put SVG into HTML, we can just use CSS classes.

### CODE REVIEW

**Comment by JanJakes** [comment]
To get some context here first - does this remove the need of a whole icon font? And if so, why the icon font itself was not removed?

Second question - would it help to include the SVG more or less like this?
```
<selector> {
  content: url("data:image/svg+xml; utf8, <svg>...</svg>");
}
```

**Comment by NeosinneR** [comment]
First part - yes, we no longer need those icon fonts. Actually, this whole issue is because they were already removed 😄 I think when we decided to slim down assets, we forgot to include these fonts. So I decided we might as well not return them.

Second part - it wouldn't help, anything that is in `background` or `content` is not selectable via CSS. 

And about using base64 or straight SVG - I tried both, but straight SVG has a little bit less support in browsers than just using base64. But it's basically the same when you decode that base64 you get the code you wrote.

**Comment by JanJakes** [comment]
👍 But is the font really missing? https://github.com/mailpoet/mailpoet/tree/master/assets/fonts

**Comment by NeosinneR** [comment]
I was really sure, that I removed them locally and git didn't show anything in status, so I thought they were already out of git. Some magic over here. But they are removed now 😉

**Pull request merged**
