### PR TITLE
Remove preheader tooltip [MAILPOET-5757]

### PR DESCRIPTION
**Pull request by pavel-mailpoet**
## Description

The tooltip in the preheader was hard to discover. It has been removed, and the help text is now below the input field. 

## Linked tickets

[MAILPOET-5757]

## QA notes

It is a new UI element, so some cross-browser check would be nice; check if the counter works appropriately, if it turns yellow after 80 characters and red after 150.

## Tasks

- [x] I followed [best practices](https://codex.wordpress.org/I18n_for_WordPress_Developers) for translations
- [x] I added sufficient test coverage
- [x] I embraced TypeScript by either creating new files in TypeScript or converting existing JavaScript files when making changes

[MAILPOET-5757]: https://mailpoet.atlassian.net/browse/MAILPOET-5757?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by lysyjan — DISMISSED** [review]
Good job!

@pavel-mailpoet There are not instructions for QA. I'm not sure if I can merge it or pass it to Veljko and Alexey.

**Comment by pavel-mailpoet** [comment]
> There are not instructions for QA. I'm not sure if I can merge it or pass it to Veljko and Alexey.

@lysyjan sorry, I am not sure what are the current practices, do you skip QA for the Gutenberg tickets? I would leave this to you at your discretion. It can go to QA, but I don't know.

**Comment by pavel-mailpoet** [comment]
@lysyjan, I added one more commit to the pull request. Can you please repeat the review? Sorry, I haven't done it before.

**Review by lysyjan — APPROVED** [review]
@pavel-mailpoet Thanks for the last improvement 👍

**Review by Aschepikov — APPROVED** [review]
GJ!

**Pull request merged**
