### PR TITLE
Add missing segment tracking [MAILPOET-5503]

### PR DESCRIPTION
**Pull request by johnolek**
## Description

This PR updates the tracking code to include usage of segments that have been added recently.

## Code review notes

_N/A_

## QA notes

_N/A_

## Linked PRs

_N/A_

## Linked tickets

_N/A_

## After-merge notes

_N/A_

## Tasks

- [x] I followed [best practices](https://codex.wordpress.org/I18n_for_WordPress_Developers) for translations
- [x] I added sufficient test coverage
- [x] I embraced TypeScript by either creating new files in TypeScript or converting existing JavaScript files when making changes

### CODE REVIEW

**Review by rodrigoprimo — APPROVED** [review]
Code changes look good to me.

I wonder if you checked if there is a way to dynamically add all existing segments to tracking instead of keeping this manual list of segments? I'm sure we will forget to update this list again in the future. I don't think we necessarily have to implement this in this PR. I'm just wondering if you checked if it is possible. Maybe we can create a separate ticket to look into this.

Feel free to move this PR to QA.

**Comment by johnolek** [comment]
Thanks for the review, @rodrigoprimo!

> I wonder if you checked if there is a way to dynamically add all existing segments to tracking instead of keeping this manual list of segments?

This is immediately where my mind went when I started working on this ticket as well. Unfortunately I couldn't think of a straightforward way to do it, especially considering there's both JS and PHP that needs to be updated. I do think it's worth looking into, perhaps as part of a larger refactoring effort. At least for the time being we've become aware of this requirement and will be on the lookout for it when reviewing PRs.

I've added a subtask to ticket MAILPOET 5227, which I created a while ago to track general refactoring/improvement tasks.

**Review by Aschepikov — APPROVED** [review]
GJ!

**Comment by rodrigoprimo** [comment]
Sounds good to me, @johnolek. Thanks.

**Pull request merged**
