### PR TITLE
Fix woocommerce setup issue [MAILPOET-5019]

### PR DESCRIPTION
**Pull request by websupporter**
[MAILPOET-5019]

[MAILPOET-5019]: https://mailpoet.atlassian.net/browse/MAILPOET-5019?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by triple0t — DISMISSED** [review]
I can still see the Automations and Upgrade sub-menu, but I don't think that is blocking. I'm approving the PR

Screenshot 2023-01-25 at 12 50 28 PM

**Comment by websupporter** [comment]
@triple0t automations and upgrade should now also be invisible.

**Review by triple0t — APPROVED** [review]
LGTM

**Review by Aschepikov — APPROVED** [review]
QA Verified

**Pull request merged**
