### PR TITLE
Normalize automation action icons [MAILPOET-6132][MAILPOET-5960]

### PR DESCRIPTION
**Pull request by NeosinneR**
## Description

This PR fixes 3 issues
1. Inconsistent padding in icons (i.e., some SVGs had padding, some were from edge to edge)
2. Blurred icons in Firefox ([MAILPOET-5960]) caused by scaling
3. Overflowing icons when in smaller boxes

The screenshots below are from a yet-to-be-merged branch, but the same format is also used on the `Analytics > Subscribers` list page.

**Before**
Screenshot 2024-06-26 at 16 58 45

**After**
Screenshot 2024-06-26 at 17 53 10

## Code review notes

_N/A_

## QA notes

Check if trigger and action icons are not missing and they are properly shown in:
- Automation editor
- Trigger/Action block popup
- Automation analytics

## Linked PRs

https://github.com/mailpoet/mailpoet-premium/pull/885

## Linked tickets

[MAILPOET-6132]
[MAILPOET-5960]

## After-merge notes

_N/A_

## Tasks

- [x] 🚫 I followed [best practices](https://codex.wordpress.org/I18n_for_WordPress_Developers) for translations
- [x] 🚫 I added sufficient test coverage
- [x] 🚫 I embraced TypeScript by either creating new files in TypeScript or converting existing JavaScript files when making changes

[MAILPOET-5960]: https://mailpoet.atlassian.net/browse/MAILPOET-5960?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MAILPOET-6132]: https://mailpoet.atlassian.net/browse/MAILPOET-6132?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MAILPOET-5960]: https://mailpoet.atlassian.net/browse/MAILPOET-5960?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by websupporter — DISMISSED** [review]
thank you @NeosinneR. lgtm

**Review by veljkho — CHANGES_REQUESTED** [review]
@NeosinneR  I do not see if else icon in the workflow, but I do see it in the right sidebar
Screenshot: https://d.pr/i/cvcrmG

**Comment by NeosinneR** [comment]
@veljkho you sure you have CSS assets built properly? This was addressed in the https://github.com/mailpoet/mailpoet/pull/5695/commits/b30e5538750d4ecbefa8bf5c3d30e1c6fb9115cf and locally I see it correctly rendered. 

Screenshot 2024-06-28 at 13 10 38

**Comment by veljkho** [comment]
Im testing it online, I will try clearing server cache (browser cache cleared)

**Comment by veljkho** [comment]
I dont see it also when using Jurassic Ninja site. @NeosinneR 
Will it work only when in production?

**Comment by NeosinneR** [comment]
@veljkho I set up a new Jurassic.ninja using the build from https://app.circleci.com/pipelines/github/mailpoet/mailpoet/18321/workflows/b3eb037d-8c9b-4cf5-9cf1-25c3ea0fb0b7/jobs/311754 and the icon is there.

Screenshot 2024-06-29 at 11 40 25

Specifically, the `.mailpoet-automation-colored-icon>div` style should be there, which is what's needed for the if/else icon to show properly. Could you please share access to the site where it's broken?

**Comment by NeosinneR** [comment]
@websupporter FYI, I force pushed the last commit https://github.com/mailpoet/mailpoet/pull/5695/commits/0e00431f475d9d9782ed0afcfd96b0c17e9be673 and added `height: 100%` and `width: 100%` because without it, it worked only in Chrome. Now, it also works in FF and Safari. No change in premium.

**Review by veljkho — APPROVED** [review]
It is good now, thanks for the fix!

**Pull request merged**
