### PR TITLE
List add/remove action [PREMIUM-214]

### PR DESCRIPTION
**Pull request by JanJakes**
## Description

_N/A_

## Code review notes

Based on https://github.com/mailpoet/mailpoet/pull/4604. Once that is merged, I'll rebase this on `trunk`.

## QA notes

_N/A_

## Linked PRs

https://github.com/mailpoet/mailpoet-premium/pull/668

## Linked tickets

[PREMIUM-214]

## After-merge notes

_N/A_

[PREMIUM-214]: https://mailpoet.atlassian.net/browse/PREMIUM-214?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by websupporter — DISMISSED** [review]
lgtm @JanJakes. Thank you!

**Review by Aschepikov — COMMENTED** [review]
@JanJakes Hi, I can't open the automation list or add new automation, because I have some console error, can you take a look pls, checked on two sites
image
image

`Uncaught TypeError: Cannot read properties of undefined (reading 'controls')
    at premium.js?ver=4.2.0:2:117575
    at premium.js?ver=4.2.0:2:117823
    at premium.js?ver=4.2.0:2:120339
    at premium.js?ver=4.2.0:2:191184`

`Uncaught (in promise) TypeError: (0 , g.apiFetch) is not a function
    at k (automation.js?ver=4.2.0:2:564898)
    at k.next (<anonymous>)
    at commons.js?ver=4.2.0:9:1571691
    at a (commons.js?ver=4.2.0:9:1571833)
    at e (commons.js?ver=4.2.0:9:1572088)
    at commons.js?ver=4.2.0:9:119600
    at new Promise (<anonymous>)
    at commons.js?ver=4.2.0:9:119580
    at commons.js?ver=4.2.0:9:119762
    at commons.js?ver=4.2.0:9:119836`

`Uncaught TypeError: Cannot read properties of undefined (reading 'call')
    at u (runtime.js?ver=4.2.0:1:153)
    at 90388 (automation_editor.js?ver=4.2.0:1:30586)
    at u (runtime.js?ver=4.2.0:1:153)
    at automation_editor.js?ver=4.2.0:1:54456
    at u.O (runtime.js?ver=4.2.0:1:486)
    at automation_editor.js?ver=4.2.0:1:54474
    at t (runtime.js?ver=4.2.0:1:2254)
    at automation_editor.js?ver=4.2.0:1:56`

**Comment by NeosinneR** [comment]
@Aschepikov did you also install the [accompanied premium](https://github.com/mailpoet/mailpoet-premium/pull/668) plugin version?

**Comment by Aschepikov** [comment]
@NeosinneR with both plugins I have this console error 
image 
But as I understand with just free plugin, part of the automation functionality should work too. Or in this case, I should check the new functionality with both plugins and don't check it with just free version?

**Comment by Aschepikov** [comment]
Sorry, I get it and fixed this console error

**Comment by NeosinneR** [comment]
> But as I understand with just free plugin, part of the automation functionality should work too.

@Aschepikov you are correct. The Automations should work even with just the free plugin (as in it should not break). This new action is visible in the free, but it's locked. And only with premium install you can use it.

**Review by Aschepikov — APPROVED** [review]
GJ!

**Pull request merged**
