### PR TITLE
Redesign - Emails - Congratulation page [MAILPOET-2833]

### PR DESCRIPTION
**Pull request by amine-mp**
[MAILPOET-2833]

[MAILPOET-2833]: https://mailpoet.atlassian.net/browse/MAILPOET-2833

### CODE REVIEW

**Review by wxa — APPROVED** [review]
Looks good. I've changed loader default size to 32px (was 34px) to match specs.

**Comment by NeosinneR** [comment]
@wxa added a few commits, when you have time, please re-review this PR, thanks :)

**Comment by wxa** [comment]
@NeosinneR One UX thing is annoying me: after clicking "Close" on the congrats page there is no visible reaction until the settings-saving AJAX request returns, there may be a lag of several seconds, so I'm tempted to click "Close" several times until I see that a page is loading. What about adding a standard loading overlay/animation?

**Comment by NeosinneR** [comment]
@wxa added spinner straight on the button, which also disables clicking on it multiple times

**Review by wxa — APPROVED** [review]

**Review by veljkho — APPROVED** [review]

**Pull request merged**
