### PR TITLE
Redesign the introduction modal for the new editor [MAILPOET-5635]

### PR DESCRIPTION
**Pull request by lysyjan**
## Description

This PR redesigns a modal for choosing between the old and new email editor. As a part of this design, a button containing a dropdown opens the redesigned modal window.

## Code review notes

I tried to use existing components from the Gutenberg package or our own when possible. This causes the dropdown menu to have a slightly bigger space on the top than in the design.

## QA notes

1. Enable a new email editor on the URL`/wp-admin/admin.php?page=mailpoet-experimental`
    1. Use an option from the dropdown for creating a new email
    2. Check that a modal is displayed
    3. Try both buttons in the displayed modal - confirmation should redirect a user to the new email editor and cancelation close the modal
2. Disable a new email editor on the URL `/wp-admin/admin.php?page=mailpoet-experimental`
    1. The button for email creation should be still the same

## Linked PRs

_N/A_

## Linked tickets

[MAILPOET-5635]

## After-merge notes

_N/A_

## Tasks

- [x] I followed [best practices](https://codex.wordpress.org/I18n_for_WordPress_Developers) for translations
- [x] I added sufficient test coverage
- [x] I embraced TypeScript by either creating new files in TypeScript or converting existing JavaScript files when making changes

[MAILPOET-5635]: https://mailpoet.atlassian.net/browse/MAILPOET-5635?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by costasovo — APPROVED** [review]
LGTM! 👍 Good job!

**Comment by lysyjan** [comment]
@veljkho @Aschepikov I have rebased this branch on trunk and committed a new image to SVN. Testing this PR before a new plugin version is released would be nice.

**Comment by Aschepikov** [comment]
Hi @lysyjan Is there a way to test the image of the modal, should I do something special? I see it now like this
image

**Comment by lysyjan** [comment]
@Aschepikov There was an emergency release on Friday that removed the image that I pushed for testing purposes. I have published the image again. Please, can you try it again?

**Comment by Aschepikov** [comment]
@lysyjan Now its perfect, thank you

**Review by Aschepikov — APPROVED** [review]
GJ!

**Pull request merged**
