### PR TITLE
adding withTemplate method to Newsletter factory [MAILPOET-1551]

### PR DESCRIPTION
**Pull request by amine-mp**
- I created the directory `tests/_data/templates` to contain the templates json files.
- When creating a newsletter using the factory, the `default` template will be used by default.
- You can use an other template by adding it to the `tests/_data/templates` directory (as `template_name.json`) and call `->withTemplate('template_name')` on the factory instance.

### CODE REVIEW

**Comment by pavel-mailpoet** [comment]
Hey @costasovo can you take a look at this? I am not sure why did we even did this? You created the function `loadBodyFrom` so why did you suggested to add `withTemplate`? Can you explain the purpose of this story?

@amine-mp I don't think renaming the json file from `newsletterWithALC.json` to `default.json` is a good idea. Because the first name explain what is inside `default.json` tells you nothing about the content.

**Comment by costasovo** [comment]
It came from a chat I had with @michelleshull . She had a problem that the factory-created newsletter doesn't sent since it has not template (or maybe body?). Now I see that we set some body to every email we create in factory so I wonder why it doesn't sent. I would say that primary problem which this issues targets is that the newsletters created by this factory are not sent. Am I right @michelleshull ?

**Comment by amine-mp** [comment]
I discussed with @michelleshull and thought that giving her a way to design templates, export them as json and use them in the tests would be the most flexible solution. That's why I created the `templates` directory and renamed the default template as `default`. Maybe I am over engineering here, but the change is small so I went for it.

**Comment by pavel-mailpoet** [comment]
You're not over engineering if you just renaming stuff. 

The thing I am asking is: why do we need this? This PR doesn't bring anything new so my question is: what did Michelle need? What couldn't she do before that she created this task?

**Pull request closed without merging**
