### PR TITLE
Email editor switch to custom editor [MAILPOET-5637]

### PR DESCRIPTION
**Pull request by costasovo**
## Description

This PR switches the email editor from a post editor to a custom Gutenberg editor. It also migrates all features we added on top of the post editor.

## Code review notes

I used the code from the research, so the PR contains all commits from the research.

## QA notes

In this, you please QA email preview added in https://github.com/mailpoet/mailpoet/pull/5204.

1. Active new email editor feature if it's disabled
2. Create a new email
3. Try if all preview options work properly (Desktop preview, Mobile preview, Preview in a new tab, send preview email).

Note 1: Email content in the preview email or preview in the new tab currently differs from the content in the editor. The email renderer functionality is covered in a separate set of tasks.
Note 2: There is a  known issue that the previews in the new tab and in the sent email contain only saved changes.

## Linked PRs

https://github.com/mailpoet/mailpoet/pull/5204

## Linked tickets

[MAILPOET-5637]

## After-merge notes

_N/A_ 

## Tasks

- [x] I followed [best practices](https://codex.wordpress.org/I18n_for_WordPress_Developers) for translations
- [x] I added sufficient test coverage
- [x] I embraced TypeScript by either creating new files in TypeScript or converting existing JavaScript files when making changes

[MAILPOET-5637]: https://mailpoet.atlassian.net/browse/MAILPOET-5637?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by lysyjan — DISMISSED** [review]
@costasovo Good job! I'm looking forward to the next steps 👍

**Review by Aschepikov — DISMISSED** [review]
GJ!

**Comment by Aschepikov** [comment]
Hi @costasovo there are some conflicts can you resolve them pls

**Comment by Aschepikov** [comment]
And if you see the problem with the send preview can you fix it in this pr?

**Review by Aschepikov — APPROVED** [review]
GJ!

**Pull request merged**
