### PR TITLE
Improve autocomplete accessibility for names in forms [MAILPOET-4408]

### PR DESCRIPTION
**Pull request by costasovo**
This PR was [originally](https://github.com/mailpoet/mailpoet/pull/4182) created by @simsekb. I've recreated it because of a CI configuration issue.

[MAILPOET-4408]

[MAILPOET-4408]: https://mailpoet.atlassian.net/browse/MAILPOET-4408?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Testing instr.
1. Make sure you have some form popup with at least First Name, Last Name and Email Address
2. Go to the front-end to see that form popup
3. Test that browser's autocomplete is working on the form fields First Name, Last Name and Email Address
Hint: This can be done by subscribing to a form, then going back to edit the form and just press Save button (to clear cookies) and going back to the same front-end page you should be able to see the form again and browser's autocompleting should work there for mentioned three fields.

### CODE REVIEW

**Review by rodrigoprimo — DISMISSED** [review]
Looks good to me. Thanks for helping improve MailPoet, @simsekb.

**Comment by simsekb** [comment]
> Looks good to me. Thanks for helping improve MailPoet, @simsekb.

No worries, we've got a lot more where that's coming from! Stay tuned haha:)

**Comment by rohankacharegs** [comment]
GlobalStep Verified

**Review by veljkho — DISMISSED** [review]

**Comment by veljkho** [comment]
Hi @costasovo 
There is some conflicting file, please resolve so I could merge. Thanks!

**Comment by costasovo** [comment]
@veljkho Thanks for the notification. Rebased!

**Review by veljkho — APPROVED** [review]

**Pull request merged**
