### PR TITLE
Homepage - Remove feature switch [MAILPOET-4831]

### PR DESCRIPTION
**Pull request by costasovo**
## Description

Draft because it waits for https://github.com/mailpoet/mailpoet/pull/4701 to get merged.

This PR:
1) Removes the feature switch and makes the homepage available as the default main page in the plugin.
2) Adds migrations for older users (set states for the task list and the engagement section)
3) Add tracking of clicks in the tasks list

## Code review notes

_N/A_

## QA notes
Please test that the behavior for existing users is correct. See details in [MAILPOET-4831]

## Linked PRs

_N/A_

## Linked tickets

[MAILPOET-4831]

## After-merge notes

_N/A_

[MAILPOET-4831]: https://mailpoet.atlassian.net/browse/MAILPOET-4831?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MAILPOET-4831]: https://mailpoet.atlassian.net/browse/MAILPOET-4831?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by samnajian — APPROVED** [review]
LGTM!

**Comment by Aschepikov** [comment]
Hi @costasovo 
The product discovery section is visible on an old site with all tasks completed. 
image
In the ticket, I see that if the all tasks are finished we should hide them. 
image

**Comment by costasovo** [comment]
> In the ticket, I see that if the all tasks are finished we should hide them.

@Aschepikov Can you please share how you tested it? I'm asking because the "hiding" of the product discovery section happens in migration, and because of that, there might be some cases when testing feature branch build zip that may cause the migration didn't trigger.

1) In case the site was once updated to the new version and then downgraded and then updated again it will cause the migration will not run again, and the section will remain visible. So for testing, you need a fresh site that never had this build installed before.
2) Or maybe the migration just didn't run because the feature branch build has the same version as the current production build. You can verify it by looking into `wp_mailpoet_migrations` table and checking that there is a row with the name `Migration_20230131_121621` and no errors. If the row is missing, the migration didn't run. You can manually trigger migrations by deactivating and reactivating the plugin.

Could you please check if 1) or 2) didn't cause that the section remained visible during testing?

**Comment by Aschepikov** [comment]
@costasovo No it was the first install and I see this migration in my db. It's hard to say why it was so because I can't repeat it without reinstalling, I will try to find another old site and check it
image

**Comment by Aschepikov** [comment]
@costasovo Yep I checked it on another very old site and I don't see this task list, GJ! But then I installed woocommerce on this site and I am not sure, should this task list be visible in this case or not?

**Comment by Aschepikov** [comment]
On one side we have two additional tasks that we need to complete for a better understanding of this integration with woocommerce, on the other side user is not a beginner. What do you think @costasovo

**Review by Aschepikov — APPROVED** [review]

**Comment by Aschepikov** [comment]
https://a8c.slack.com/archives/C01H71ZLBGQ/p1678712499572369 discussion here

**Pull request merged**
