### PR TITLE
Feat/show email engagement badges for key metrics - MAILPOET-4688

### PR DESCRIPTION
**Pull request by triple0t**
## Description

Show email engagement badges for key metrics. 

* Show  badge for opens and clicks on the email listing page
* Show badge for opens, unsubscribed, and bounces on advanced email statistics page

## Code review notes

* Kind reminder to run `./do compile:all`

## QA notes

For the badge, you need the following minimum requirements
* minimum Newsletters Sent = 20;
* minimum Newsletters Opened = 5;
* minimum Unsubscribed Count = 5;
* minimum Bounced Count = 5;
* minimum Newsletters Sent for showing Unsubscribed and Bounced badge = 100;

## Linked tickets

[MAILPOET-4688](https://mailpoet.atlassian.net/browse/MAILPOET-4688)

### CODE REVIEW

**Review by lysyjan — DISMISSED** [review]
LGTM

**Review by Aschepikov — COMMENTED** [review]
There is an issue with badges with unsubscribed and bounced
image
image
image

**Comment by veljkho** [comment]
I would add that there are cases when everything's fine with the stats, [like this one](https://d.pr/i/7LaI9J).
No idea what could cause Excellent badge to show up for 20,30+ %, maybe when it is so high that it turns to be Excellent? Not really sure.

**Comment by triple0t** [comment]
Hi @Aschepikov, Thank you for the review

> There is an issue with badges with unsubscribed and bounced

Fixed. 
As you would notice in the screenshot shared, the numbers have a `comma` in them instead of a `full stop`. This is probably due to your locale.

In addition,

We need a minimum of 100 newsletters sent before showing the unsubscribed and bounced badge.

We calculate these stats using micro value (0.3, 0.5, etc) and at low volumes (less than 50 newsletters) the percentages and badges can be misleading.

**Review by Aschepikov — APPROVED** [review]
Verified, GJ!

**Pull request merged**
