### PR TITLE
Update the dev env, tests and Circle CI to run with PHP 8.2 as default [MAILPOET-4620]

### PR DESCRIPTION
**Pull request by costasovo**
## Description

This PR updates the dev env, tests, and Circle CI to run with PHP 8.2 as the default

## Code review notes

I hope I have addressed all related places.

## QA notes

I think we can skip QA.

## Linked PRs

https://github.com/mailpoet/mailpoet-premium/pull/920

## Linked tickets

[MAILPOET-4620]

## After-merge notes

Ping #mailpoet-dev to rebuild their container in dev-env. Run `docker compose build wordpress`

## Tasks

- [ ] I followed [best practices](https://codex.wordpress.org/I18n_for_WordPress_Developers) for translations
- [ ] I added sufficient test coverage
- [ ] I embraced TypeScript by either creating new files in TypeScript or converting existing JavaScript files when making changes

[MAILPOET-4620]: https://mailpoet.atlassian.net/browse/MAILPOET-4620?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

## Preview

[Preview in WordPress Playground](https://account.mailpoet.com/playground/new/branch:update-php-to-82)

_The latest successful build from `update-php-to-82` will be used. If none is available, the link won't work._

### CODE REVIEW

**Review by triple0t — DISMISSED** [review]
LGTM
Please feel free to merge when ready

**Comment by triple0t** [comment]
@costasovo  A tiny note here 
https://github.com/mailpoet/mailpoet/blob/f28cc4e012f084f6c928fccff23bea3d0aa9c733/.circleci/config.yml#L99-L102
Does .org support PHP 8.2?

**Comment by costasovo** [comment]
> @costasovo A tiny note here
> [mailpoet/.circleci/config.yml](https://github.com/mailpoet/mailpoet/blob/f28cc4e012f084f6c928fccff23bea3d0aa9c733/.circleci/config.yml#L99-L102)
> Lines 99 to 102 in [f28cc4e](https://github.com/mailpoet/mailpoet/commit/f28cc4e012f084f6c928fccff23bea3d0aa9c733)
>  wpcli_php_max_wporg: 
   <<: *default_job_config 
   docker: 
     - image: mailpoet/wordpress:8.2_20231016.1 
> Does .org support PHP 8.2?

@triple0t Good question. The job is passing https://app.circleci.com/pipelines/github/mailpoet/mailpoet/19353/workflows/54e8333a-8e61-429f-bc23-89f50cf9fce4/jobs/330021 so the rules code supports PHP 8.2 but I'm not 100% that running it on PHP 8.2 influences the output as there could be some conditions in the rules.

**Comment by triple0t** [comment]
> > @costasovo A tiny note here
> > [mailpoet/.circleci/config.yml](https://github.com/mailpoet/mailpoet/blob/f28cc4e012f084f6c928fccff23bea3d0aa9c733/.circleci/config.yml#L99-L102)
> > Lines 99 to 102 in [f28cc4e](https://github.com/mailpoet/mailpoet/commit/f28cc4e012f084f6c928fccff23bea3d0aa9c733)
> > wpcli_php_max_wporg:
> > <<: *default_job_config
> > docker:
> > - image: mailpoet/wordpress:8.2_20231016.1
> > Does .org support PHP 8.2?
> 
> @triple0t Good question. The job is passing https://app.circleci.com/pipelines/github/mailpoet/mailpoet/19353/workflows/54e8333a-8e61-429f-bc23-89f50cf9fce4/jobs/330021 so the rules code supports PHP 8.2 but I'm not 100% that running it on PHP 8.2 influences the output as there could be some conditions in the rules.

@costasovo, I guess my question wasn't very clear. I mean, have you confirmed PHP8.2 syntax works on WordPress.org?
 
If I recall correctly, we added the circleci test and lint rules to enforce this check and confirm whatever code we are pushing to the .org repository works as expected.
This was due to an incident we had when trying to release the plugin. We pushed a code to the .org repo, which was rejected because the .org system runs lint on PHP versions below 8.1. This was back then, and the system now runs on 8.1. 
I want to confirm we won't face the same issue again.

For example: you can test by pushing a readonly class (or any [other PHP8.2 feature](https://www.php.net/releases/8.2/en.php)) to the repository and checking if you receive any error

**Comment by costasovo** [comment]
> @costasovo, I guess my question wasn't very clear. I mean, have you confirmed PHP8.2 syntax works on WordPress.org?

@triple0t Got it! I asked a team working on .org backend via Slack. I'm waiting for their reply and if they use lower version I'll switch it back.

**Comment by costasovo** [comment]
@triple0t In the end, I tried to push readonly class syntax from PHP8.2 to the repository and got an error. So I switched the PHP version for `wpcli_php_max_wporg` back to PHP8.1.

**Review by triple0t — APPROVED** [review]
LGTM. 
Jan is about to create the plugin release so we can merge the PR after the release.
Thank you for checking and confirming

**Pull request merged**
