### PR TITLE
Update wp and woo version [MAILPOET-5527]

### PR DESCRIPTION
**Pull request by websupporter**
## Description
Updates tested up to and minimum versions for WooCommerce and WordPress.

Minimum WP Version: 6.1
Minimum Woo Version: 7.8.0
Current WP Version: 6.2
Current Woo Version: 8.0.0

Followed the instructions PcD9cT-4b0-p2

## QA notes

> When creating the PR to update the version in the tags, check with QA if they want to do a final round of testing.

## Linked PRs

https://github.com/mailpoet/mailpoet-premium/pull/765

## Linked tickets

[MAILPOET-5527]

[MAILPOET-5527]: https://mailpoet.atlassian.net/browse/MAILPOET-5527?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by rodrigoprimo — CHANGES_REQUESTED** [review]
I'm not sure if something changed, but I believe that per https://mailpoet.atlassian.net/browse/MAILPOET-5226 and pcD9cT-4dg-p2, we should take this opportunity to start using an L-1 policy instead of L-2. What do you think?

**Comment by websupporter** [comment]
Thanks for the hint. Updated to L1 @rodrigoprimo

**Review by rodrigoprimo — DISMISSED** [review]
Looks good to me. Thanks for updating the versions to L-1. I went ahead and updated the documentation page to remove references to the old L-2 policy (PcD9cT-4b0-p2).

**Comment by Aschepikov** [comment]
HI @websupporter there are some conflicts can you resolve them pls

**Comment by websupporter** [comment]
Resolved & Rebased @Aschepikov

**Review by Aschepikov — APPROVED** [review]
GJ!

**Pull request merged**
