### PR TITLE
Make the labels in form editor consistent - MAILPOET-4650

### PR DESCRIPTION
**Pull request by triple0t**
## Description

Make the labels in the form editor consistent. 

## Linked tickets

[MAILPOET-4650](https://mailpoet.atlassian.net/browse/MAILPOET-4650)

### CODE REVIEW

**Review by websupporter — CHANGES_REQUESTED** [review]
Thank you @triple0t 

Looks good to me. Just one remark:
image


I think we can get rid of the CSS definitions for `.form-editor-sidebar-heading`

**Comment by triple0t** [comment]
Thanks for the review, @websupporter  🙌🏿

> I think we can get rid of the CSS definitions for `.form-editor-sidebar-heading`

I initially thought this was coming from Gutenberg and might be used by other components, so I left it alone.

Taking a deeper look, It would appear the CSS class was used for specific purposes (I noticed it was defined in two separate files). Rather than removing it, I would instead add the class back.

I will push a new commit to reflect that now.

**Review by websupporter — APPROVED** [review]
lgtm. Thank you @triple0t

**Review by Aschepikov — APPROVED** [review]
Verified, GJ!

**Pull request merged**
