### PR TITLE
Automation fixes [MAILPOET-5242][MAILPOET-4968][MAILPOET-5377]

### PR DESCRIPTION
**Pull request by JanJakes**
## Description

A couple of automation-related fixes:
1. Tutorial was visible in emails of type `automation_transactional` ([MAILPOET-5242]).
2. A few React warnings and popover positioning.
3. Save/update automation unified with WP post editor, added keyboard shortcut ([MAILPOET-4968]).
4. Include category parents in category fields ([MAILPOET-5377]).

## Code review notes

_N/A_

## QA notes

_N/A_

## Linked PRs

https://github.com/mailpoet/mailpoet-premium/pull/762

## Linked tickets

[MAILPOET-5242]
[MAILPOET-4968]
[MAILPOET-5377]

## After-merge notes

_N/A_

## Tasks

- [x] I followed [best practices](https://codex.wordpress.org/I18n_for_WordPress_Developers) for translations
- [x] I added sufficient test coverage
- [x] I embraced TypeScript by either creating new files in TypeScript or converting existing JavaScript files when making changes

[MAILPOET-5242]: https://mailpoet.atlassian.net/browse/MAILPOET-5242?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MAILPOET-4968]: https://mailpoet.atlassian.net/browse/MAILPOET-4968?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MAILPOET-5377]: https://mailpoet.atlassian.net/browse/MAILPOET-5377?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MAILPOET-5242]: https://mailpoet.atlassian.net/browse/MAILPOET-5242?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MAILPOET-4968]: https://mailpoet.atlassian.net/browse/MAILPOET-4968?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MAILPOET-5377]: https://mailpoet.atlassian.net/browse/MAILPOET-5377?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by alex-mpoet — COMMENTED** [review]
Looks good overall! 

Minor things I noticed:
* The "Saving" icon is slightly misaligned (Chrome, Firefox):
saving-icon-misaligned
* Categories selector doesn't update categories on the fly if you add them while editing an automation, you have to refresh the page.

**Comment by JanJakes** [comment]
@alex-mpoet Thanks!

> The "Saving" icon is slightly misaligned (Chrome, Firefox):

I agree that it looks strange, but it's the icon, I guess. This is from WP post editor (same as in automations):

Screenshot 2023-08-11 at 10 49 36

> Categories selector doesn't update categories on the fly if you add them while editing an automation, you have to refresh the page.

Can we add new categories anywhere in the automation editor? I don't think we have such functionality yet, neither for tags. We could consider creating a ticket for that.

I noticed two more small issues, so I added two new commits.

**Comment by alex-mpoet** [comment]
@JanJakes 
> Can we add new categories anywhere in the automation editor? I don't think we have such functionality yet, neither for tags. We could consider creating a ticket for that.

I mean categories are preloaded at page load and aren't dynamically fetched on typing like we do with lists in many places. So if I create a product category in another tab in WooCommerce, it doesn't show up in the automation editor unless the page is refreshed. No need to create Woo product categories in the editor.

**Comment by JanJakes** [comment]
@alex-mpoet Right, the problem here is that this is not easy without implementing some kind of lazy/async/parametrized field option loading in automations. We'll probably need that for long lists anyway, but it's at least a medium feature, not a quick fix.

**Review by alex-mpoet — DISMISSED** [review]

**Comment by Aschepikov** [comment]
Hi @JanJakes there are some conflicts can you resolve them pls

**Review by Aschepikov — APPROVED** [review]
GJ!

**Pull request merged**
