### PR TITLE
Send posts published before post notification has been created [MAILPOET-1560]

### PR DESCRIPTION
**Pull request by pavel-mailpoet**

### CODE REVIEW

**Comment by wxa** [comment]
1. Have a few posts published some time ago.
2. Create a new post notification to be sent immediately, make sure these posts are in a preview.
3. Activate the notification. 
4. According to new specs it should be scheduled and sent. Doesn't happen. Looks like PN scheduling is triggered by publishing new posts only.

**Comment by pavel-mailpoet** [comment]
Just to want to be sure: @qfrery can you answer if that is the behaviour you want?

**Comment by qfrery** [comment]
@wxa I understand the problem. Is it possible to force the trigger when the new post notification has been created ? If possible, I don't what to wait until new post has been published to start the trigger

**Comment by qfrery** [comment]
Not really
I want 4. to be: A post notification is schedule and will be sent at the next post notification due date (the day after, the week after, etc).

Make sense?

**Comment by pavel-mailpoet** [comment]
@wxa I updated this Pull Request according to your comments :)

**Pull request merged**
