### PR TITLE
Rebranding typography [MAILPOET-3548]

### PR DESCRIPTION
**Pull request by NeosinneR**
[MAILPOET-3548]

[MAILPOET-3548]: https://mailpoet.atlassian.net/browse/MAILPOET-3548

### CODE REVIEW

**Comment by NeosinneR** [comment]
@j111q I completely removed our custom font and changed font sizes and colors to match with WordPress admin. Just a note that this and button changes are in separate branches, so in the screenshots below, there are still MailPoet branded buttons.

Screenshot 2021-06-02 at 15 49 32
Screenshot 2021-06-02 at 15 50 11
Screenshot 2021-06-02 at 15 50 46
Screenshot 2021-06-02 at 15 52 21
Screenshot 2021-06-02 at 15 52 29
Screenshot 2021-06-02 at 15 52 39
Screenshot 2021-06-02 at 15 54 12
Screenshot 2021-06-02 at 15 55 35
Screenshot 2021-06-02 at 16 00 49

**Review by j111q — DISMISSED** [review]
Looks great!!!! 👏  Sad to see the friendly rounded font go, but it does look so much more cohesive with the rest of the interface. Thanks @NeosinneR !

**Review by pavel-mailpoet — DISMISSED** [review]

**Review by veljkho — CHANGES_REQUESTED** [review]
Something is still in blue color:
1. Newsletter statistics page ([some text like date, to, from, reply.. products sold part](https://d.pr/i/VEYpXW), [order total](https://d.pr/i/hs5pH4)).
2. [Status circle and numbers 9 / 9](https://d.pr/i/YAgbm9) & [Opened/Clicked percentages](https://d.pr/i/YAgbm9) from the newsletter listing pages.

Everything else seems fine.

**Comment by NeosinneR** [comment]
@veljkho everything should be dark gray now. I completely removed the blue color from the code.

**Review by veljkho — APPROVED** [review]

**Pull request merged**
