### PR TITLE
Prevent stale/orphaned Doctrine data when using DQL/SQL [MAILPOET-5845]

### PR DESCRIPTION
**Pull request by JanJakes**
## Description

This is a more proper fix and refactor of https://github.com/mailpoet/mailpoet/pull/5374, plus a few more improvements and entity manager clearing between runs.

See also: https://mailpoetdev.wordpress.com/2024/01/19/issue-with-stuck-post-notifications/

## Code review notes

_N/A_

## QA notes

Please, test that post notifications get scheduled and sent (and don't get stuck). Please, try a larger list, if possible.

It would also be good to smoke test other types of sending, and background jobs.

## Linked PRs

_N/A_

## Linked tickets

[MAILPOET-5845]

## After-merge notes

_N/A_

## Tasks

- [x] I followed [best practices](https://codex.wordpress.org/I18n_for_WordPress_Developers) for translations
- [x] I added sufficient test coverage
- [x] I embraced TypeScript by either creating new files in TypeScript or converting existing JavaScript files when making changes

[MAILPOET-5845]: https://mailpoet.atlassian.net/browse/MAILPOET-5845?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by alex-mpoet — COMMENTED** [review]
@JanJakes Looks good overall!

But I'm seeing all these `deleteByNewsletterIds()` (and variations like `removeNewsletterDataByNewsletterIds()`, `newsletterRepository->deleteByIds()`) methods duplicated in so many repositories, they differ only in class name passed to them, can they be unified and extracted to a trait?

**Comment by JanJakes** [comment]
@alex-mpoet That's a good idea. It makes me think, if I can add some sort of more generic helper to the parent repository class for these bulk actions. I'll check it out.

**Comment by JanJakes** [comment]
@alex-mpoet I tried to use [Doctrine Criteria](https://www.doctrine-project.org/projects/doctrine-collections/en/stable/expression-builder.html) for this to automatically do both deletes and the in-memory cleanup, such as:

```php
// in any repository
$this->deleteAll(new Criteria(Criteria::expr()->in('id', $ids)));
```

The idea is that I could apply criteria to the SQL query (query builder) as well as to the in memory data (collection). I [implemented it](https://github.com/mailpoet/mailpoet/tree/doctrine-bulk-actions-criteria), but during testing, I realized the criteria evaluation for collections was poorly implemented and I couldn't reliably use it. There were issues, such as the inability to use IDs for relations (I needed to fetch entity references), and even worse, their `IN` operator compares objects non-strictly (like `==`), which recurses the whole object tree and can cause infinite depth with circular references.

So, I threw that away and wanted to try a trait, but that's not easy either, because the `deleteByNewsletterIds` calls parent repository function (`detachAll`), and needs private properties (`$this->entityManager`).

So, I think I would leave it this way for now. We'll see what more we'll need to do, regarding the Doctrine bulk actions.

**Review by alex-mpoet — APPROVED** [review]
Thanks for looking into it and trying to fix it! I agree, it's worth looking into Doctrine bulk actions later to see if any improvements are possible.

**Review by Aschepikov — APPROVED** [review]
GJ!

**Pull request merged**
