### PR TITLE
Update removeOrphanedSubscribers() query to work with WooCommerce Custom Orders Tables [MAILPOET-4569]

### PR DESCRIPTION
**Pull request by rodrigoprimo**
## Description

This PR should be reviewed after #4388 is merged as it contains some commits from the other PR.

It updates the method \MailPoet\Segments\WooCommerce::removeOrphanedSubscribers() to use a different query if WooCommerce Custom Orders Tables is enabled.

## Code review notes

Install MailPoet in a WooCommerce shop that already has a few orders placed by guest customers. Configure MailPoet to synchronize WooCommerce customers as MailPoet subscribers and check that subscribers are created for the WooCommerce guest customers.

The above should work when testing with WooCommerce Custom Order Tables disabled (default behavior) and with WooCommerce Custom Order Tables enabled and the synchronization with the old tables disabled. Instructions on how to install WooCommerce, enable COT, and disable the synchronization can be found in this link: https://github.com/woocommerce/woocommerce/wiki/High-Performance-Order-Storage-Upgrade-Recipe-Book#easy-way

## QA notes

_N/A_

## Linked PRs

_N/A_

## Linked tickets

[MAILPOET-4569]

## After-merge notes

_N/A_

[MAILPOET-4569]: https://mailpoet.atlassian.net/browse/MAILPOET-4569?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by costasovo — DISMISSED** [review]
I did check the last two commits and the changes look good to me!

**Review by Aschepikov — DISMISSED** [review]
GJ! Resolve conflicts needed @rodrigoprimo

**Comment by rodrigoprimo** [comment]
Thanks, @Aschepikov. I have rebased this PR. Could you please approve it again and merge it? After rebasing, we lose the previous approvals.

**Review by Aschepikov — APPROVED** [review]
Ready

**Pull request merged**
