### PR TITLE
Bump WooCommerce version to 8.1

### PR DESCRIPTION
**Pull request by brezocordero**
## Description

Updates tested up to and minimum version for WooCommerce.

## Code review notes

Might need to wait for [MAILPOET-5588]

## QA notes

_N/A_

## Linked PRs

_N/A_

## Linked tickets

[MAILPOET-5589]

## After-merge notes

_N/A_

## Tasks

- [x] I followed [best practices](https://codex.wordpress.org/I18n_for_WordPress_Developers) for translations
- [x] I added sufficient test coverage
- [ ] I embraced TypeScript by either creating new files in TypeScript or converting existing JavaScript files when making changes -> NA

[MAILPOET-5588]: https://mailpoet.atlassian.net/browse/MAILPOET-5588?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MAILPOET-5589]: https://mailpoet.atlassian.net/browse/MAILPOET-5589?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by rodrigoprimo — COMMENTED** [review]
I'm inclined to agree that we should wait for [MAILPOET-5588] before moving this PR forward, or was MailPoet already tested with Woo 8.1 somehow?

**Comment by brezocordero** [comment]
> or was MailPoet already tested with Woo 8.1 somehow?

It was tested until 8.1.0-rc.1. It started failing with 8.1.0-rc.2 and 8.1

**Comment by rodrigoprimo** [comment]
Slack discussion about how to proceed with this PR and the related ticket: p1695058331017919-slack-C01H71ZLBGQ

We will wait a bit to learn more about [MAILPOET-5588] before merging this PR.

[MAILPOET-5588]: https://mailpoet.atlassian.net/browse/MAILPOET-5588?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by brezocordero** [comment]
@rodrigoprimo the tests are running [on the latest version again.](https://github.com/mailpoet/mailpoet/commit/f5ee3b9736f11c8d2f1a29e880f3198fce8ce88d)

**Review by rodrigoprimo — APPROVED** [review]

**Pull request merged**
