### PR TITLE
Automation email sidebar [MAILPOET-4420]

### PR DESCRIPTION
**Pull request by JanJakes**
[MAILPOET-4420]

[MAILPOET-4420]: https://mailpoet.atlassian.net/browse/MAILPOET-4420?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by alex-mailpoet** [comment]
@JanJakes First round of feedback:

1. Is it intended that subject and preheader are multi-line (textarea)?
2. When I click on "Design email", nothing happens.

image

**Comment by JanJakes** [comment]
@alex-mailpoet Thanks!

1. That's how it was designed in Figma. But yeah, what to do with newlines? Any ideas, @NeosinneR?
2. There will be a template selection screen, so I thought we could implement it only later, together with that. Also, https://github.com/mailpoet/mailpoet/pull/4239 was not merged at that time so I skipped. Should we handle it now or do it separately? 🤔

**Comment by alex-mailpoet** [comment]
@JanJakes 

> Should we handle it now or do it separately? 🤔

This PR is already huge, let's do it separately.

**Comment by NeosinneR** [comment]
1. Discussed in [Slack](https://a8c.slack.com/archives/C0313447YBC/p1658142399923449), we'll keep textareas, as long as new lines are disabled and can't be used (neither by typing nor by pasting).

**Review by alex-mailpoet — COMMENTED** [review]
@JanJakes Please fix the multi-line issue mentioned by @NeosinneR, otherwise looks good!

**Review by alex-mailpoet — APPROVED** [review]

**Review by veljkho — APPROVED** [review]

**Review by veljkho — APPROVED** [review]

**Pull request merged**
