### PR TITLE
Upgrade @woocommerce/components to version 12.1 [PREMIUM-231]

### PR DESCRIPTION
**Pull request by JanJakes**
## Description

This is based on https://github.com/mailpoet/mailpoet/pull/5047, but tries to untangle some of the complexities and simplify some hacks.

Closes https://github.com/mailpoet/mailpoet/pull/5047.

## Code review notes

_N/A_

## QA notes

WooCommerce components are used:
- automation listing page
- automation analytics
- the "MailPoet Marketing Opt-in" block

It might be useful to test also the premium plugin if "everything" still works. I have especially the Automations UI in mind.

## Linked PRs

[PREMIUM-231]

## Linked tickets

_N/A_

## After-merge notes

_N/A_

## Tasks

- [x] I followed [best practices](https://codex.wordpress.org/I18n_for_WordPress_Developers) for translations
- [x] I added sufficient test coverage
- [x] I embraced TypeScript by either creating new files in TypeScript or converting existing JavaScript files when making changes

[PREMIUM-231]: https://mailpoet.atlassian.net/browse/PREMIUM-231?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by websupporter** [comment]
I am currently getting this "fatal" error:
`currency_1.CurrencyFactory is not a function`

In my investigation, it originates from `@woocommerce/components/build/filters/index.js`
image

I `console.log`ged the value of `currency_1`:
image

**Comment by JanJakes** [comment]
@websupporter Ahh, interesting. I was getting this from the CJS build. Also, `@woocommerce/components/build` points to CJS, while I thought `@woocommerce/components/build-module` is the one that's currently used 🤔

Did you indeed pull the latest (force-pushed) branch, run `./do install` and `./do compile:all`?

**Comment by JanJakes** [comment]
@websupporter Ahh, I can replicate that now 🤔 Will check.

**Comment by JanJakes** [comment]
@websupporter Was just a rebase, fixed. Also fixed one prop-type warning.

**Comment by websupporter** [comment]
Thank you @JanJakes. Overall looks good to me. Something weired is going on with the DatePicker:

https://github.com/mailpoet/mailpoet/assets/6458412/92faa09b-e34c-4674-b17c-db57bfcd124e

If you want, I can have a closer look after my AFK.

**Comment by JanJakes** [comment]
@websupporter Ahh, this is due to https://github.com/woocommerce/woocommerce/pull/37034 duplicating some of our `@wordpress` dependencies to an older version. I had to add [yet another hack](https://github.com/mailpoet/mailpoet/pull/5060/commits/a519bdce13dee4df781b3b735f7215fcf8b6711f#diff-294bd10db07c43b10b4271610c9181fa32e67317ac9a373f495793f0ce8441f2) to prevent this, but ultimately, we should adopt the same strategy for WP components and externalize them from our bundles.

**Comment by JanJakes** [comment]
Linking this to a related WooCommerce issue: https://github.com/woocommerce/woocommerce/issues/39345

**Comment by Aschepikov** [comment]
Hi @JanJakes I see the unknown error occurred on the analytics page, can you check it?
image (6)

**Comment by JanJakes** [comment]
@Aschepikov Hmm, do you know if we have the same error on `trunk`? It seems to come from PHP, which this PR doesn't touch 🤔 Checking...

**Comment by Aschepikov** [comment]
@JanJakes I didn't see this error on the trunk or on the next prs

**Comment by JanJakes** [comment]
@Aschepikov I can replicate an error, but it seems to be unrelated to this PR and fixed in https://github.com/mailpoet/mailpoet/pull/5055. So I guess we need to verify if it's OK once this and https://github.com/mailpoet/mailpoet/pull/5055 are both merged.

**Comment by Aschepikov** [comment]
@JanJakes Ok, thank you

**Review by Aschepikov — APPROVED** [review]
GJ! Error is fixed on the https://github.com/mailpoet/mailpoet/pull/5055

**Pull request merged**
