### PR TITLE
Segment number opens [MAILPOET-3224]

### PR DESCRIPTION
**Pull request by pavel-mailpoet**
[MAILPOET-3224]

[MAILPOET-3224]: https://mailpoet.atlassian.net/browse/MAILPOET-3224

### CODE REVIEW

**Review by costasovo — CHANGES_REQUESTED** [review]
Good job! 👍  I have just a couple of small remarks.

**Review by costasovo — DISMISSED** [review]
👍

**Review by veljkho — APPROVED** [review]
UI is looking good. 👍 
Even the functionality, but except this small issue.

The point 2.c. is not respected here properly.. I can't enter zero value and save the segment, giving me the error message "Please fill all required values".

But, since this is a cosmetic issue it's better to merge this and have in tomorrow's release, and I'll open separate ticket.

**Comment by veljkho** [comment]
Branch conflict present.

**Review by veljkho — APPROVED** [review]

**Pull request merged**
