### PR TITLE
Add tob bar and notifications to the homepage [MAILPOET-4825]

### PR DESCRIPTION
**Pull request by costasovo**
## Description
This PR adds the standard top bar and support for important notices we want to show users on the main page of the plugin.

Supported notices are:

1. All notices that are defined in [PermanentNotices.php](https://github.com/mailpoet/mailpoet/blob/3318dd90b167d4d70a2d20f6a30d1217400ea65b/mailpoet/lib/Util/Notices/PermanentNotices.php#L83-L116)
2. Dynamic notices that can be shown in JS via `MailPoet.Notice`
3. Standard WordPress notices
4. Custom made notices we add via JS (see screenshot)

Screenshot 2022-12-09 at 14 44 51

## Code review notes
I recommend going commit by commit.

## QA notes
You need to go to `/wp-admin/admin.php?page=mailpoet-experimental` and enable the feature.

## Linked PRs

_N/A_

## Linked tickets
[MAILPOET-4825]

## After-merge notes

_N/A_

[MAILPOET-4835]: https://mailpoet.atlassian.net/browse/MAILPOET-4835?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MAILPOET-4825]: https://mailpoet.atlassian.net/browse/MAILPOET-4825?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by triple0t — COMMENTED** [review]
Looks good and works well.
Well done, @costasovo 

~I have a question: Why did we decide to start showing Newsletter specific notices on other pages? ([done in this commit](https://github.com/mailpoet/mailpoet/pull/4609/commits/3318dd90b167d4d70a2d20f6a30d1217400ea65b))~

It's in the Ticket spec. I will ask my question on it.

**Review by triple0t — DISMISSED** [review]

**Review by Aschepikov — COMMENTED** [review]
Hi, there are some conflicts, can you resolve them pls

**Comment by costasovo** [comment]
@Aschepikov Thanks for the ping! I fixed the conflict.

**Review by Aschepikov — APPROVED** [review]
GJ!

**Pull request merged**
