### PR TITLE
Link the default privacy policy from the default form templates - MAILPOET-4651

### PR DESCRIPTION
**Pull request by triple0t**
## Description

Link the default privacy policy from the default form templates

Add the replacePrivacyLinkTags method for Form Templates. 

## QA notes

Set privacy policy page here: /wp-admin/options-privacy.php

## Linked tickets

[MAILPOET-4651](https://mailpoet.atlassian.net/browse/MAILPOET-4651)

### CODE REVIEW

**Review by brezocordero — CHANGES_REQUESTED** [review]
Hi @triple0t 
As we talked, please check if we need to [esc_url](https://developer.wordpress.org/reference/functions/esc_url/)
Thanks!

**Comment by triple0t** [comment]
> As we talked, please check if we need to [esc_url](https://developer.wordpress.org/reference/functions/esc_url/)

@brezocordero Fixed.

Thank you

**Review by brezocordero — APPROVED** [review]
Works great.
Thanks for making the change.

**Review by Aschepikov — APPROVED** [review]
Verified, GJ!

**Pull request merged**
